Algoritmo "ex1Para"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : fazer a multiplicação por 3 , durante 5 vezes (função)
// Autor(a)    : Silvio Gabriel
// Data atual  : 15/09/2023
Var
   // Seção de Declarações das variáveis
   numero:inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...



   para numero de 1 ate 10 passo 1 faca
        escreval(numero)
   fimpara


Fimalgoritmo