Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/09/2023


Var

   graos, contador: real



Inicio

   graos<-1

   contador<-1



   repita

      escreval(contador,"-",graos)

      contador<-contador+1//2

      graos<-graos*2//2



   ate contador>64





Fimalgoritmo