Algoritmo "ExWord13"
// Disciplina : Lógica de programação
// Professor: Jailson 
// Descrição   : Faça um programa que solicite o nome do usuário e exiba uma mensagem de saudação.(função)
// Autor(a)    : Silvio Gabriel
// Data atual  : 22/09/2023
Var
// Seção de Declarações das variáveis
nome:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Escreva o seu nome: ")
leia(nome)

escreva("Olá, seja bem-vindo(a) ",nome)


Fimalgoritmo